In [3]:
#CREATINING A EMPTY AND FULL NUMPY ARRAY:-
import numpy as np

# Create an empty numpy array
empty_array = np.empty((3, 3))  

# Create a full numpy array with a specific value
full_array = np.full((3, 3), 7)  

print("Empty Array:")
print(empty_array)

print("\nFull Array:")
print(full_array)


Empty Array:
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.52166653e-321]
 [6.01346930e-154 7.26606878e+223 1.10639944e+200]]

Full Array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [3]:
    #REMOVING A ROWS IN NUMPY ARRAY THAT CONTAINS NON NUMARIC VALUES:

    # Create a sample numpy array with mixed data types
    data = np.array([[1, 2, 3],
                     [4, 'five', 6],
                     [7, 8, 9],
                     ['ten', 'eleven', 'twelve']])

    # Function to check if a value is numeric
    def is_numeric(value):
        try:
            float(value)
            return True
        except (ValueError, TypeError):
            return False

    # Apply the is_numeric function to each element of the array
    numeric_mask = np.vectorize(is_numeric)(data)

    # Use boolean indexing to select only rows containing numeric values
    numeric_rows = data[numeric_mask.all(axis=1)]

    print("Original Array:")
    print(data)

    print("\nArray with Non-Numeric Rows Removed:")
    print(numeric_rows)


Original Array:
[['1' '2' '3']
 ['4' 'five' '6']
 ['7' '8' '9']
 ['ten' 'eleven' 'twelve']]

Array with Non-Numeric Rows Removed:
[['1' '2' '3']
 ['7' '8' '9']]


In [4]:
#Finding the number of occurrences of a sequence in a NumPy array


# Create a sample numpy array
arr = np.array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3])

# Define the sequence you want to find
sequence_to_find = np.array([1, 2, 3,4])

# Initialize a count variable to keep track of occurrences
count = 0

# Loop through the array and search for the sequence
for i in range(len(arr) - len(sequence_to_find) + 1):
    if np.array_equal(arr[i:i+len(sequence_to_find)], sequence_to_find):
        count += 1

print(f"Number of occurrences of {sequence_to_find}: {count}")


Number of occurrences of [1 2 3 4]: 2


In [5]:
#FINDING A SUM OF TWO ARRAYS:-

# Create two sample numpy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Calculate the element-wise sum of the two arrays
result_array = array1 + array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Sum os array 1 and arra 2 is:",result_array)


Array 1: [1 2 3]
Array 2: [4 5 6]
Sum os array 1 and arra 2 is: [5 7 9]


In [6]:
#RETURNS THE INDICIES OF ELEMENTS WHERE THE GIVEN CONDITION IN SATISFIED:-

# Create a sample numpy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

condition = arr > 5

# Use boolean indexing to get the indices where the condition is satisfied
indices = np.where(condition)

# Print the indices
print("Indices where the condition is satisfied:", indices)


Indices where the condition is satisfied: (array([5, 6, 7, 8], dtype=int64),)


In [7]:
#MULTIPLICATION WITH SCALAR:-


# Create a sample numpy matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Define the scalar you want to multiply the matrix by
scalar = 2

# Multiply the matrix by the scalar using the * operator
result_matrix = matrix * scalar

print("Original Matrix:")
print(matrix)

print("\nMatrix after Multiplication by Scalar:")
print(result_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix after Multiplication by Scalar:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
#Array re-dimensioning of giving data:-
import numpy as np

# Given numpy array
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

# Reshape the array to the desired shape 
new_shape = (3, 2)
reshaped_array = a.reshape(new_shape)

print("Original Array:")
print(a)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]

Reshaped Array:
[[2.5  3.8 ]
 [1.5  4.7 ]
 [2.9  1.56]]


In [9]:
#Obtaining Boolean Array from Binary Array of given data:


# Given binary array
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

# Create a boolean array based on the binary array
boolean_array = a.astype(bool)

print("Binary Array:")
print(a)

print("\nBoolean Array:")
print(boolean_array)


Binary Array:
[[1 0 0]
 [1 1 1]
 [0 0 0]]

Boolean Array:
[[ True False False]
 [ True  True  True]
 [False False False]]


In [10]:
#HORIZONTAL STACKING OF NUMPY ARRAY:-
# Create two sample numpy arrays
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Horizontally stack the arrays
stacked_array = np.hstack((array1, array2))

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nHorizontally Stacked Array:")
print(stacked_array)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Horizontally Stacked Array:
[[1 2 5 6]
 [3 4 7 8]]


In [11]:
#ARRAY GENERATION OF RANDOM INTEGERS:-



low_range = 1 
high_range = 10  
array_size = (3, 4)  


random_integers = np.random.randint(low_range, high_range, size=array_size)

print("Random Integer Array:")
print(random_integers)


Random Integer Array:
[[9 6 2 7]
 [6 8 3 7]
 [4 6 8 9]]


In [13]:
#MULTIPLICATION OF ARRAY:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
c=a*b
print("After Multiplication:\n",c)

After Multiplication:
 [[ 2  6 12]
 [20 30 42]
 [56 72 90]]


In [1]:
"hii"

'hii'

In [2]:
a=4
b=5
c=a+b
print("sum is:",c)

sum is: 9
